import { Crop } from '../types';

export const SUPPORTED_CROPS: Crop[] = [
  {
    id: 'crop-rice',
    name: 'Rice',
    scientificName: 'Oryza sativa',
    icon: '🌾',
    category: 'Cereal',
    commonDiseases: ['Bacterial Leaf Blight', 'Brown Spot', 'Leaf Blast', 'Sheath Blight'],
    description: 'Staple cereal crop grown across wetland paddy ecosystems.',
  },
  {
    id: 'crop-wheat',
    name: 'Wheat',
    scientificName: 'Triticum aestivum',
    icon: '🌾',
    category: 'Cereal',
    commonDiseases: ['Brown Rust', 'Yellow Rust', 'Powdery Mildew'],
    description: 'Rabi cereal grain sensitive to humidity rust outbreaks.',
  },
  {
    id: 'crop-maize',
    name: 'Maize',
    scientificName: 'Zea mays',
    icon: '🌽',
    category: 'Cereal',
    commonDiseases: ['Common Rust', 'Gray Leaf Spot', 'Northern Leaf Blight'],
    description: 'High-yield coarse grain vulnerable to foliar blights and stem borers.',
  },
  {
    id: 'crop-tomato',
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    icon: '🍅',
    category: 'Vegetable',
    commonDiseases: ['Early Blight', 'Late Blight', 'Bacterial Spot', 'Leaf Mold', 'Yellow Leaf Curl Virus'],
    description: 'High-value horticultural crop sensitive to leaf blights and humidity rot.',
  },
  {
    id: 'crop-potato',
    name: 'Potato',
    scientificName: 'Solanum tuberosum',
    icon: '🥔',
    category: 'Tuber',
    commonDiseases: ['Early Blight', 'Late Blight'],
    description: 'Tuber crop prone to late blight defoliation in moist cloudy weather.',
  },
  {
    id: 'crop-chilli',
    name: 'Chilli',
    scientificName: 'Capsicum annuum',
    icon: '🌶️',
    category: 'Spice',
    commonDiseases: ['Anthracnose', 'Leaf Curl Virus', 'Powdery Mildew'],
    description: 'Spice crop affected by pod rot anthracnose and whitefly vector viral curls.',
  },
  {
    id: 'crop-soybean',
    name: 'Soybean',
    scientificName: 'Glycine max',
    icon: '🫛',
    category: 'Legume',
    commonDiseases: ['Bacterial Blight', 'Soybean Rust', 'Leaf Spot'],
    description: 'Kharif oilseed legume sensitive to rust spore drift.',
  },
  {
    id: 'crop-groundnut',
    name: 'Groundnut',
    scientificName: 'Arachis hypogaea',
    icon: '🥜',
    category: 'Oilseed',
    commonDiseases: ['Early Leaf Spot', 'Late Leaf Spot', 'Groundnut Rust'],
    description: 'Subterranean oilseed susceptible to tikka leaf spot defoliation.',
  },
  {
    id: 'crop-chickpea',
    name: 'Chickpea',
    scientificName: 'Cicer arietinum',
    icon: '🫘',
    category: 'Pulse',
    commonDiseases: ['Fusarium Wilt', 'Ascochyta Blight', 'Botrytis Grey Mould'],
    description: 'Rabi pulse crop vulnerable to vascular wilt and grey mould.',
  },
  {
    id: 'crop-cotton',
    name: 'Cotton',
    scientificName: 'Gossypium hirsutum',
    icon: '☁️',
    category: 'Fiber',
    commonDiseases: ['Bacterial Blight', 'Alternaria Leaf Spot', 'Fusarium Wilt'],
    description: 'Commercial cash fiber crop prone to leaf spot and black arm disease.',
  },
];
